# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ hook ]
  pull_request:
    branches: [ hook ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "javiergimenezsanchez@gmail.com"
        git config --global user.name "xavigimenezsanchez"
        git remote set-url origin https://${{ secrets.TokenHook }}@github.com/xavigimenezsanchez/install-test.git
        npm run deploy
